package net.alshanex.magic_realms.util.chat_system;

public enum PersonalityTrait {
    BRAVE, SHY, CONFIDENT, HUMOROUS, SERIOUS,
    FRIENDLY, RESERVED, CURIOUS, CAUTIOUS,
    OPTIMISTIC, PESSIMISTIC, EMPATHETIC, LOGICAL,
    CREATIVE, PRACTICAL, ADVENTUROUS, HOMELY,
    FORGIVING, GRUDGE_HOLDER, INTELLECTUAL, SIMPLE,
    MYSTICAL, GROUNDED, CUNNING, HONEST,
    COMPETITIVE, COOPERATIVE, MYSTERIOUS
}
